import streamlit as st
import time

from streamlit_extras.app_logo import add_logo
from Methods import Methods as mtd
from Constants import Constants as ct

st.set_page_config(
    page_title="Similarity",
    page_icon="🍿",
    layout="wide",
    initial_sidebar_state="expanded",
)
add_logo("logo.png",120)
st.markdown(ct.PAGE_LAYOUT, unsafe_allow_html=True)

#Page title
st.title("Generate the best movie/series recommendation that's similar to your favorite title.🍿",anchor=False)
st.divider()

submitted = False

#Text input for Movie/Series title
title = st.sidebar.text_input('Title', 'Avatar (2009)',help="""
                        The title of a Movie/Series that you want the recommendations to be similar to.
                        The released year is optional, but best to include it for search accuracy. 
                        E.g. Avatar (2009), The Matrix (1999), The Terminator (1984), etc.""")

#Text area for user's likings of the title
likings = st.sidebar.text_area(
"What do you like about it?",
"Great world building, beautiful environments, incredibly lifelike exotic creatures, "
"the imagery is engulfing.",
max_chars=200, help="""Briefly state what you like about the given title. 
                        Include the characteristic or element from your given title (seperated with commas if multiple) 
                        that you want the recommendations to have.
                        E.g. "beautiful environments", "action packed", "high-stakes", etc.
                        """,placeholder="(Optional)")

#Radio button for recommendation type
type = st.sidebar.radio(
    "Recommendation type",
    ("Movie", "Series", "Both"),
    horizontal=True,
    help="Choose the entertainment type that you want the recommendation to be generated by.")

#Max amount of output
max = st.sidebar.slider('Max recommendation', 1, 10, 5,
                help="Pick the maximum amount of recommendation that you want to be generated.")

#Submit button
if st.sidebar.button('Generate',use_container_width=True):
    if title == "":
        alert = st.sidebar.warning('Title text field is empty', icon="⚠️")
        time.sleep(3)
        alert.empty()
    else:
        st.toast('Submitted for generation...')
        if likings == "":
            likings = f"the characteristic or element similar to the {title}"
        with st.spinner('Generating recommendations, please wait... 🍵'):
            time.sleep(5)
            recommendation = mtd.generate_similarity(title,likings,type,max)
            if recommendation:
                submitted = True
                st.toast('Recommendations generated!')

#When submitted
if submitted:
    mtd.mainOutput(recommendation)