import streamlit as st
import time

from streamlit_extras.app_logo import add_logo
from Methods import Methods as mtd

add_logo("logo.png",120)

#Page title
st.title("Generate random movie/series for new discovery.🔀",anchor=False)
st.divider()

submitted = False

category = st.sidebar.radio(
    "Pick your poison",
    ("Popular", "Underrated","Any"),
    horizontal=True,
    help="Choose the category that you want the recommendation to be generated by.")

#Max amount of output
max = st.sidebar.slider('Max recommendation', 1, 10, 5,
                help="Pick the maximum amount of recommendation that you want to be generated.")

#Radio button for recommendation type
type = st.sidebar.radio(
    "Recommendation type",
    ("Movie", "Series", "Both"),
    horizontal=True,
    help="Choose the entertainment type that you want the recommendation to be generated by.")

#Submit button
if st.sidebar.button('Generate',use_container_width=True):
    with st.spinner('Generating recommendations, please wait... 🍵'):
        st.toast('Submitted for generation...')
        time.sleep(5)
        recommendation = mtd.generate_random(category,type,max)
        if recommendation:
            submitted = True
            st.toast('Recommendations generated!')

#When submitted
if submitted:
    with st.expander("📃View as list"):
        list = "\n".join([f"{i+1}. {item}" for i, item in enumerate(recommendation)])
        st.write(list)
    for element in recommendation:
            parts = element.split(" (")
            t = parts[0]
            y = element[element.find("(")+1 : element.find(")")]
            data = mtd.getData(t,y)
            if data["Response"] == "True":
                if data["Poster"] == "N/A":
                    data["Poster"] = "https://www.reelviews.net/resources/img/default_poster.jpg"
                mtd.createComponent(
                data["Title"],
                data["Released"],
                data["imdbRating"],
                data["Poster"],
                data["Plot"],
                data["Type"],
                data["imdbID"],
                data["Director"],
                data["Genre"]
                )

    submitted = False